### ISSUE TITLE
%2f sendo reconhecido como caminho da url

### ISSUE THREAD

**Issue by luisviniciuslv** [Bielgomes/Fastipy#2]
Na hora de receber um parametro na url, por exemplo:

```py
@app.get("fat/:ncod")
ncod = req.params['ncod']
```

O ncod é por seria `2024/12345`. Obviamente não posso passar uma "/" no parâmetro, então o padrão seria substituir por "%2f". Mas ao fazer uma requisição seguindo esse padrão, ele reconhece como se fosse um path da url.

![image](https://github.com/user-attachments/assets/2340e739-8e79-4376-a78d-a50a5b1fe7f9)

**Comment by Bielgomes** [comment]
Fix: #8
